name: build

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        # https://github.com/microsoft/vscode-platform-specific-sample/blob/main/.github/workflows/ci.yml
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          - os: windows-latest
            platform: win32
            arch: ia32
            npm_config_arch: ia32
          - os: windows-latest
            platform: win32
            arch: arm64
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: armhf
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: alpine
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Environment
        run: |
          node -v
          npm -v
          npm --version

      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV

      - name: Install
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          npm_config_arch: ${{ matrix.npm_config_arch }}
          TARGET: ${{ env.target }}
        run: npm install

      - name: Lint
        run: |
          npm run lint

      - name: Compile
        run: npm run compile

      - uses: axetroy/setup-whatchanged@v1
        with:
          version: v0.4.1

      - name: Generate CHANGELOG.md
        run: whatchanged HEAD~ > CHANGELOG.md

      - name: Package
        run: npx vsce package --target ${{ env.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.target }}
          path: "*.vsix"

  release:
    runs-on: ubuntu-latest
    name: "Release to vscode market and github"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.repository == 'release-lab/vscode-whatchanged'
    needs: ci
    steps:
      - uses: actions/download-artifact@v2

      - run: tree

      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:RELEASE_NOTE

      - uses: softprops/action-gh-release@v1
        name: publish to Github
        env:
          # require Github Personal Access Token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          body: ${{ env.RELEASE_NOTE }}
          files: |
            alpine-x64/*.vsix
            darwin-arm64/*.vsix
            darwin-x64/*.vsix
            linux-arm64/*.vsix
            linux-armhf/*.vsix
            linux-x64/*.vsix
            win32-arm64/*.vsix
            win32-ia32/*.vsix
            win32-x64/*.vsix
          draft: false

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: publish to vscode market
        run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.ADO_TOKEN }}
