name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          - os: windows-latest
            platform: win32
            arch: ia32
            npm_config_arch: ia32
          - os: windows-latest
            platform: win32
            arch: arm64
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: armhf
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: alpine
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Environment
        run: |
          node -v
          npm -v
          yarn --version

      - name: Install
        run: |
          yarn

      - name: Lint
        run: |
          npm run lint

      - name: Compile
        run: |
          yarn run compile

      - uses: axetroy/setup-whatchanged@v1
        with:
          version: v0.4.1

      - name: Generate CHANGELOG.md
        run: |
          whatchanged HEAD~ > CHANGELOG.md

      - name: Package
        run: |
          npx vsce package -o ./vscode-whatchanged.vsix

      - uses: actions/upload-artifact@v2
        if: runner.os == 'linux'
        with:
          name: package
          path: ./vscode-whatchanged.vsix

  release:
    runs-on: ubuntu-latest
    name: "Release to vscode market and github"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.repository == 'whatchanged-community/vscode-whatchanged'
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package

      - uses: softprops/action-gh-release@v1
        name: publish to Github
        env:
          # require Github Personal Access Token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            ./vscode-whatchanged.vsix
          draft: false

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: publish to vscode market
        # require Azure DevOps Personal Access Token
        run: npx vsce publish --packagePath ./vscode-whatchanged.vsix --pat ${{ secrets.ADO_TOKEN }}
